from exceptions_1.exercises import case_1


def main():
    print('Start up')

    case_1()

    print("Finish")


if __name__ == '__main__':
    main()
